import 'package:get/get.dart';
import '../models/designer.dart';

class DesignerController extends GetxController {
  //Designer와 카테고리에따라 분류된 filteredDesigner들만 관리
  static DesignerController get to => Get.find();
  List<Designer> _designerList = [];
  List<Designer> get designerList => _designerList;

  List<Designer> _filteredList = [];
  List<Designer> get filteredList => _filteredList;

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
    _filteredList = [
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_1.jpeg',
        designerName: '강아지 디자이너',
        shopName: '네일킹',
        shopAddress: '세종시 한솔동',
        shopLat: 36.478460,
        shopLng: 127.260958,
        portfolioCount: 100,
        viewCount: 2400,
        likeCount: 30,
        designList: [
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_2.jpeg',
        designerName: '강아지 실장',
        shopName: '정훈네일',
        shopAddress: '대전시 유성구 궁동',
        shopLat: 36.481050,
        shopLng: 127.260407,
        portfolioCount: 100,
        viewCount: 2800,
        likeCount: 70,
        designList: [
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_3.jpeg',
        designerName: '고양이 디자이너',
        shopName: '첫마을네일',
        shopAddress: '대전시 대덕구 장대동',
        shopLat: 36.480755,
        shopLng: 127.263533,
        portfolioCount: 10,
        viewCount: 2600,
        likeCount: 50,
        designList: [
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_4.jpeg',
        designerName: '다람쥐 원장',
        shopName: '가재네일',
        shopAddress: '세종시 종촌동',
        shopLat: 36.504625,
        shopLng: 127.247219,
        portfolioCount: 100,
        viewCount: 2400,
        likeCount: 50,
        designList: [
          'assets/images/nail_image_10.jpeg',
          'assets/images/nail_image_11.jpeg',
          'assets/images/nail_image_12.jpeg',
          'assets/images/nail_image_13.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
    ];
    _designerList = [
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_1.jpeg',
        designerName: '강아지 디자이너',
        shopName: '네일킹',
        shopAddress: '세종시 한솔동',
        shopLat: 36.478460,
        shopLng: 127.260958,
        portfolioCount: 100,
        viewCount: 2400,
        likeCount: 30,
        designList: [
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_2.jpeg',
        designerName: '강아지 실장',
        shopName: '정훈네일',
        shopAddress: '대전시 유성구 궁동',
        shopLat: 36.481050,
        shopLng: 127.260407,
        portfolioCount: 100,
        viewCount: 2800,
        likeCount: 70,
        designList: [
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_3.jpeg',
        designerName: '고양이 디자이너',
        shopName: '첫마을네일',
        shopAddress: '대전시 대덕구 장대동',
        shopLat: 36.480755,
        shopLng: 127.263533,
        portfolioCount: 10,
        viewCount: 2600,
        likeCount: 50,
        designList: [
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_4.jpeg',
        designerName: '다람쥐 원장',
        shopName: '가재네일',
        shopAddress: '세종시 종촌동',
        shopLat: 36.504625,
        shopLng: 127.247219,
        portfolioCount: 100,
        viewCount: 2400,
        likeCount: 50,
        designList: [
          'assets/images/nail_image_10.jpeg',
          'assets/images/nail_image_11.jpeg',
          'assets/images/nail_image_12.jpeg',
          'assets/images/nail_image_13.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_1.jpeg',
        designerName: '강아지 디자이너',
        shopName: '네일킹',
        shopAddress: '세종시 한솔동',
        shopLat: 36.478460,
        shopLng: 127.260958,
        portfolioCount: 100,
        viewCount: 2400,
        likeCount: 30,
        designList: [
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_2.jpeg',
        designerName: '강아지 실장',
        shopName: '정훈네일',
        shopAddress: '대전시 유성구 궁동',
        shopLat: 36.481050,
        shopLng: 127.260407,
        portfolioCount: 100,
        viewCount: 2800,
        likeCount: 70,
        designList: [
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_3.jpeg',
        designerName: '고양이 디자이너',
        shopName: '첫마을네일',
        shopAddress: '대전시 대덕구 장대동',
        shopLat: 36.480755,
        shopLng: 127.263533,
        portfolioCount: 10,
        viewCount: 2600,
        likeCount: 50,
        designList: [
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_4.jpeg',
        designerName: '다람쥐 원장',
        shopName: '가재네일',
        shopAddress: '세종시 종촌동',
        shopLat: 36.504625,
        shopLng: 127.247219,
        portfolioCount: 100,
        viewCount: 2400,
        likeCount: 50,
        designList: [
          'assets/images/nail_image_10.jpeg',
          'assets/images/nail_image_11.jpeg',
          'assets/images/nail_image_12.jpeg',
          'assets/images/nail_image_13.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_1.jpeg',
        designerName: '강아지 디자이너',
        shopName: '네일킹',
        shopAddress: '세종시 한솔동',
        shopLat: 36.478460,
        shopLng: 127.260958,
        portfolioCount: 100,
        viewCount: 2400,
        likeCount: 30,
        designList: [
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_2.jpeg',
        designerName: '강아지 실장',
        shopName: '정훈네일',
        shopAddress: '대전시 유성구 궁동',
        shopLat: 36.481050,
        shopLng: 127.260407,
        portfolioCount: 100,
        viewCount: 2800,
        likeCount: 70,
        designList: [
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_3.jpeg',
        designerName: '고양이 디자이너',
        shopName: '첫마을네일',
        shopAddress: '대전시 대덕구 장대동',
        shopLat: 36.480755,
        shopLng: 127.263533,
        portfolioCount: 10,
        viewCount: 2600,
        likeCount: 50,
        designList: [
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
      Designer(
        locationCity: '대전광역시',
        imageUrl: 'assets/images/user_image_4.jpeg',
        designerName: '다람쥐 원장',
        shopName: '가재네일',
        shopAddress: '세종시 종촌동',
        shopLat: 36.504625,
        shopLng: 127.247219,
        portfolioCount: 100,
        viewCount: 2400,
        likeCount: 50,
        designList: [
          'assets/images/nail_image_10.jpeg',
          'assets/images/nail_image_11.jpeg',
          'assets/images/nail_image_12.jpeg',
          'assets/images/nail_image_13.jpeg',
          'assets/images/nail_image_1.jpeg',
          'assets/images/nail_image_2.jpeg',
          'assets/images/nail_image_3.jpeg',
          'assets/images/nail_image_4.jpeg',
          'assets/images/nail_image_5.jpeg',
          'assets/images/nail_image_6.jpeg',
          'assets/images/nail_image_7.jpeg',
          'assets/images/nail_image_8.jpeg',
          'assets/images/nail_image_9.jpeg',
        ],
      ),
    ];
    update();
  }

  void filterDesigner() {
    //이후 여기에서 필터링하는 작업을 거칠예정 ( 필터링 하기위한 값들은 filter_designer_controller에서 가져온값들 위주로)
  }
}
