name: common
description: SWF team2
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.0.11
  carousel_slider: ^4.0.0
  flutter_datetime_picker: ^1.5.1
  http: ^0.13.4
  image_picker: ^0.8.4+4
  cached_network_image: ^3.2.0
  crypto: ^3.0.1
  url_launcher: ^6.0.18

  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5

  kakao_flutter_sdk: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic